### ISSUE TITLE
Colcon clean does not work

### ISSUE THREAD

**Issue by Flova** [colcon/colcon-top-level-workspace#3] opened 2024-01-23 14:25 UTC
Building works fine, but I get the following output when I run `colcon clean workspace` in a subfolder (`/homes/17vahl/colcon_ws_mono/src/bitbots_meta` in the traceback) 

```shell
colcon clean workspace                            
Using workspace root /homes/17vahl/colcon_ws_mono
Paths:
[1.892s] colcon ERROR colcon clean: '/homes/17vahl/colcon_ws_mono/build' is not in the subpath of '/homes/17vahl/colcon_ws_mono/src/bitbots_meta' OR one path is relative and the other is absolute.
Traceback (most recent call last):
  File "/homes/17vahl/.local/lib/python3.10/site-packages/colcon_core/command.py", line 522, in verb_main
    rc = context.args.main(context=context)
  File "/homes/17vahl/.local/lib/python3.10/site-packages/colcon_clean/subverb/workspace.py", line 58, in main
    clean_paths(
  File "/homes/17vahl/.local/lib/python3.10/site-packages/colcon_clean/subverb/__init__.py", line 235, in clean_paths
    path = path.relative_to(cwd_path)
  File "/usr/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/homes/17vahl/colcon_ws_mono/build' is not in the subpath of '/homes/17vahl/colcon_ws_mono/src/bitbots_meta' OR one path is relative and the other is absolute.
```

**Comment by cottsay** [comment] 2024-02-09 22:20
This was resolved yesterday by a change to `colcon-clean`.

Duplicate of colcon/colcon-clean#37

**Closed by cottsay** 2024-02-09 22:20 UTC
